### ISSUE TITLE
Create blueprint figma file

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-skeleton#14]
# General Support Request

The auro-skeleton requires a blueprint supporting document to be released to Figma. 

## Support request

Review the current state of the auro-skeleton design and create the Figma blueprint document. 

## Possible Solution

Design to review current UI for new design opportunities 

## Exit criteria 

- [x] complete blueprint work
- [x] signoff from Auro engineering (add name of reviewer) 
- [ ] add link completed version of auro-badge blueprint

**Comment by leeejune** [comment]
Changes released
