### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-skeleton#15]
The following items are to be included with the next MAJOR release of the Auro WC-Generator, all PRs are to be from the feature branch to `2.0-rc` branch.

- [ ] https://github.com/AlaskaAirlines/auro-skeleton/issues/12
- [ ] https://github.com/AlaskaAirlines/auro-skeleton/issues/10
- [ ] https://github.com/AlaskaAirlines/auro-skeleton/issues/11
- [ ] https://github.com/AlaskaAirlines/auro-skeleton/issues/14
- [ ] https://github.com/AlaskaAirlines/auro-skeleton/issues/16

**Comment by braven112** [comment]
Closing this rc in favor of issues and milestones
