### ISSUE TITLE
WCAG 2.1 Graphics Contrast Ratio

### ISSUE THREAD

**Issue by Dayna-A** [AlaskaAirlines/auro-skeleton#16]
## Describe the feature

Since WCAG 2.1 adds a contrast ratio of 3.1 for graphics and user interface components against adjacent colors, does this mean that the auro-skeleton component (with a ratio of Contrast Ratio 1.03:1) is not WCAG 2.1 compliant when used on light backgrounds? or does this qualify as an [inactive UI component](https://www.w3.org/TR/WCAG21/#non-text-contrast)?

_The scope of this feature is to revisit this component, assess its a11y support and recommend feature enhancements if applicable._

## To Reproduce

1. Visit [Webaim Contrast Checker](https://webaim.org/resources/contrastchecker/)
1. Use the Webaim.org contrast ratio checker to compare #f9fbfc (a.k.a. --auro-color-brand-neutral-100) on a background of #ffffff

**Comment by MattSidor** [comment]
For reference, here is an example from our current project.

![Kapture 2021-09-10 at 11 06 39](https://user-images.githubusercontent.com/6138182/132898401-dbbebf2d-3670-4e3e-8c3d-08b985e5d04a.gif)

**Comment by Dayna-A** [comment]
![](https://thefader-res.cloudinary.com/private_images/w_640,c_limit,f_auto,q_auto:eco/DYsRzMgVQAEblU6_gbapjp/squat-and-squint-meme-woman.jpg)
