### ISSUE TITLE
Create figma design pages for use with the doc site

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-skeleton#18]
## Reference issue

Created a blueprint with updated design: https://www.figma.com/file/16Ep0sRVQKMsAxu7vZ3wgt/Skeleton?node-id=322%3A298

Main update is the change of the base color (neutral-100 --> gray-200).

@blackfalcon Please review!

_Originally posted by @leeejune in https://github.com/AlaskaAirlines/auro-skeleton/issues/16#issuecomment-981957073_

## Spec

Create new design resource markdown pages that can be included in the Auro docsite for designer reference.

**Comment by leeejune** [comment]
Will be adding DO's and DON'T's in blueprints.

**Comment by blackfalcon** [comment]
> Will be adding DO's and DON'T's in blueprints.

@leeejune can you validate if this work was completed?

**Comment by leeejune** [comment]
@blackfalcon It has not. If it can be added to a sprint, I can work on it.
