### ISSUE TITLE
auro-skeleton: use of deprecated @alaskaairux/webcorestylesheets@3.7.3

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-skeleton#22]
# General Support Request
This component has a dependency on a deprecated version of the wcss.

Please update from @alaskaairux/webcorestylesheets@3.7.3 to latest (@aurodesignsystem/webcorestylesheets@5.0.4 or later)

**Comment by blackfalcon** [comment]
This project is still a Node 12 environment. We should do a complete update of the repo to support Node 20 and all dependencies.

**Comment by blackfalcon** [comment]
This issue is a duplicate of 

- https://github.com/AlaskaAirlines/auro-skeleton/issues/23
